version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
    db:
        image: 'mongo'
        restart: always
        ports:
            - "27017-27019:27017-27019"
        expose:
            - 27017-27019
        environment:
            - MONGO_INITDB_DATABASE=ntf
            - MONGO_INITDB_ROOT_USERNAME=troindx
            - MONGO_INITDB_ROOT_PASSWORD=1234
        networks:
            - app-tier 
        volumes:
            - ./mongo-volume:/data/db
            - ./ops/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

